config/routes.rb
Rails.application.routes.draw do
  namespace :api, { format:'json' } do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :destroy, :update] do
        member do
          get :feed, :following, :followers
        end
      end
    end
  end
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    resources :messages, only: [:index, :show, :create, :destroy]
    member do
      get :following, :followers
    end
    resources :dev_apps
    resources :linked_apps, only: [:index, :new, :create, :destroy]
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only:[:new, :create, :edit, :update]
  resources :microposts, only:[:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/dev_app.rb
class DevApp < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :app_name, presence: true, length: { maximum: 100 }
  VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :contact_mail, presence:true, length: { maximum: 250 }, format: { with: VALID_EMAIL_REGEX }
  validates :consumer_id, presence: true, length: { maximum: 50 }
  validates :consumer_secret, presence: true, length: { maximum: 100 }
  validates :callback_url, presence: true, length: { maximum: 350 }

  
end

app/controllers/dev_apps_controller.rb
class DevAppsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user,   only: :destroy

  def index
    @developer = User.find(params[:user_id])
    @dev_apps = @developer.dev_apps.paginate(page:params[:page])
  end

  def show
    @dev_app = DevApp.find(params[:id])
  end

  def new
    @developer = User.find(params[:user_id])
    @dev_app = @developer.dev_apps.build(contact_mail: @developer.email)
  end

  def create
    @dev_app = current_user.dev_apps.build(dev_app_params)
    @dev_app.consumer_id = new_token
    @dev_app.consumer_secret = new_token + new_token
    if @dev_app.save
      flash[:success] = "Application Registered! Consumer ID is #{@dev_app.consumer_id} Consumer Secret is #{@dev_app.consumer_secret}"
      redirect_to user_dev_apps_url
    else
      render 'new'
    end
  end

  def edit
    @dev_app = DevApp.find(params[:id])
  end

  def update
    @dev_app = DevApp.find(params[:id])
    @dev_app.consumer_secret = new_token + new_token if params[:reissue_secret]
    if @dev_app.update_attributes(edit_dev_app_params)
      flash[:success] = "Update information! Consumer ID is #{@dev_app.consumer_id} Consumer Secret is #{@dev_app.consumer_secret}"
      redirect_to user_dev_apps_url
    else
      render 'edit'
    end
  end

  def destroy
    @dev_app.destroy
    flash[:success] = "Deleted the registration"
    redirect_to user_dev_apps_url
  end

  private
    def dev_app_params
      params.require(:dev_app).permit(:app_name, :contact_mail, :callback_url)
    end

    def edit_dev_app_params
      params.require(:dev_app).permit(:app_name, :contact_mail, :callback_url)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end

    def correct_user
      @dev_app = current_user.dev_apps.find_by(id: params[:id])
      if @dev_app.nil?
        flash[:danger] = "Cannot delete the app"
        redirect_to user_dev_apps_url
      end
    end
end

app/helpers/dev_apps_helper.rb
module DevAppsHelper
end

app/views/dev_apps/_edit_form.html.slim
= form_for(@dev_app, url: user_dev_app_path) do |f|
  = render 'shared/error_messages', object: f.object

  = f.label :app_name
  = f.text_field :app_name, class:'form-control'

  = f.label :contact_mail
  = f.email_field :contact_mail, class:'form-control'

  = f.label :callback_url
  = f.text_field :callback_url, class:'form-control'

  = f.label :follow_notice, class: "checkbox inline" do
    = check_box_tag :reissue_secret
    span Do you want to reissue consumser secret?

  = f.submit yield(:button_text), class: "btn btn-success"

app/views/dev_apps/_form.html.slim
= form_for(@dev_app, url: user_dev_apps_path) do |f|
  = render 'shared/error_messages', object: f.object

  = f.label :app_name
  = f.text_field :app_name, class:'form-control'

  = f.label :contact_mail
  = f.email_field :contact_mail, class:'form-control'

  = f.label :callback_url
  = f.text_field :callback_url, class:'form-control'

  = f.submit yield(:button_text), class: "btn btn-success"

app/views/dev_apps/edit.html.slim
- provide(:title, 'Edit Registration')
- provide(:button_text, 'Update')
h1 Edit Registration

.row
  .col-md-6.col-md-offset-3
    = render 'edit_form'

app/views/dev_apps/index.html.slim
- provide(:title, @developer.name)
h1 Registered Apps

= link_to "Register App", new_user_dev_app_path, class: 'btn btn-success'

= will_paginate @dev_apps

table.table
  thead.thead-default
    tr
      th #
      th App Name
      th Callback URL
      th Date
      th Delete
  - @dev_apps.each_with_index do |dev_app, i|
    tr
      th scope="row" #{i+1}
      td
        = link_to dev_app.app_name, user_dev_app_path(user_id:dev_app.user_id, id:dev_app.id)
      td
        a href="#{dev_app.callback_url}" #{dev_app.callback_url}
      td
        = dev_app.created_at.strftime('%Y/%m/%d')
      td
        = link_to "delete", user_dev_app_path(user_id:dev_app.user_id, id:dev_app.id), method: :delete

= will_paginate @dev_apps

app/views/dev_apps/new.html.slim
- provide(:title, 'Register Application')
- provide(:button_text, 'Register')
h1 Register Application

.row
  .col-md-6.col-md-offset-3
    = render 'form'

app/views/dev_apps/show.html.slim
- provide(:title, "Application Information")
h1 Application Information

table.table
  thead.thead-default
    tr
      th Items
      th Information
  tbody
    tr
      th scope="row" App Name
      td
        = @dev_app.app_name
    tr
      th scope="row" Contact Mail
      td
        = @dev_app.contact_mail
    tr
      th scope="row" Consumer ID
      td
        = @dev_app.consumer_id
    tr
      th scope="row" Consumer Secret
      td
        = @dev_app.consumer_secret
    tr
      th scope="row" Callback URL
      td
        = @dev_app.callback_url
.dev-app-show
  = link_to "Back", user_dev_apps_url, class: 'btn btn-primary'
  = link_to "Edit", edit_user_dev_app_path, class: 'btn btn-success'