config/routes.rb
Rails.application.routes.draw do
  namespace :api, { format:'json' } do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :destroy, :update] do
        member do
          get :feed, :following, :followers
        end
      end
    end
  end
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    resources :messages, only: [:index, :show, :create, :destroy]
    member do
      get :following, :followers
    end
    resources :dev_apps
    resources :linked_apps, only: [:index, :new, :create, :destroy]
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only:[:new, :create, :edit, :update]
  resources :microposts, only:[:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/linked_app.rb
class LinkedApp < ApplicationRecord
  belongs_to :user
  belongs_to :dev_app
  validates :user_id, presence: true
  validates :dev_app_id, presence: true
  # validates :access_token, length: { maximum: 100 }
end

app/controllers/linked_apps_controller.rb
class LinkedAppsController < ApplicationController
  before_action :logged_in_user, only: [:index, :destroy]
  before_action :correct_link, only: :destroy

  def index
    @user = User.find(params[:user_id])
    @linked_apps = @user.linked_apps.paginate(page:params[:page])
  end

  def new
    @accept_user = User.new
    @user = User.find(params[:user_id])
    @consumer = DevApp.find_by(consumer_id: params[:consumer_id])
    @signature = params[:signature]
    redirect_to request.referrer || root_url unless check_consumer_id_and_signature?(@consumer, @signature)
  end

  def create
    @user = current_user || authenticate_user
    if @user == nil
      flash[:danger] = "Sorry... Cannot logged in. Please logged in again!"
      @accept_user = User.new
      render 'new'
    else
      dev_app_id = params[:dev_app_id].to_i
      @linked_app = @user.linking_apps.build(dev_app_id: dev_app_id)
      if @linked_app.save
        flash[:success] = "Accept Application!"
        @consumer = DevApp.find(dev_app_id)
        redirect_to @consumer.callback_url
      else
        flash[:danger] = "Sorry... Cannot accept application."
        @accept_user = User.new
        render 'new'
      end
    end
  end

  def destroy
    @linking_app.destroy
    flash[:success] = "Deleted the registration"
    redirect_to user_linked_apps_url
  end

  private
    def check_consumer_id_and_signature?(consumer, signature)
      if consumer
        key = consumer.consumer_secret
        value = consumer.consumer_id
        digest = OpenSSL::HMAC.new(value, 'sha256')
        if signature == digest.update(key).to_s
          return true
        end
      end
      return false
    end

    def correct_link
      @linking_app = current_user.linking_apps.find_by(user_id: params[:user_id], dev_app_id: params[:id])
      if @linking_app.nil?
        flash[:danger] = "Cannot delete the link"
        redirect_to user_linked_apps_url
      end
    end

    def authenticate_user
      if params[:accept_user] == nil
        return nil
      end
      user_params = params.require(:accept_user).permit(:email, :password)
      user = User.find_by(email: user_params[:email])
      return user if user.authenticate(user_params[:password])
      return nil
    end
end

app/helpers/linked_apps_helper.rb
module LinkedAppsHelper
end

app/views/linked_apps/index.html.slim
- provide(:title, "Linked Apps")
h1 Linked Apps

= will_paginate @linked_apps

table.table
  thead.thead-default
    tr
      th #
      th App Name
      th App's URL
      th Linked Date
      th Delete
  - @linked_apps.each_with_index do |link_app, i|
    tr
      th scope="row" #{i+1}
      td
        = link_app.app_name
      td
        a href="#{link_app.callback_url}" #{link_app.callback_url}
      td
        = link_app.created_at.strftime('%Y/%m/%d')
      td
        = link_to "delete", user_linked_app_path(user_id:@user.id, id:link_app.id), method: :delete

= will_paginate @linked_apps

app/views/linked_apps/new.html.slim
- provide(:title, "Authorize Application")
h1 Authorize Application

.row
  .col-md-6.col-md-offset-3
    = form_for(@accept_user, url: user_linked_apps_path) do |f|
      = render 'shared/error_messages', object: f.object
      .permission.bg-info
        p.permit-text Do you give permission below to the application?
        p.permit-text  - your profile, following, follower
        p.permit-text  - your micropsts, feeds
      - unless logged_in?
        = f.label :email
        = f.email_field :email, class:'form-control'

        = f.label :password
        = f.password_field :password, class:'form-control'

      = hidden_field_tag :dev_app_id, @consumer.id

      = f.submit "Accept", class: "btn btn-primary"
      = link_to "Deny", root_url, class: 'btn btn-danger deny-btn'